is.num = (arg) => typeof arg === "number",
is.nan = (arg) => isNaN(arg),
is.str = (arg) => typeof arg === "string",
is.bool = (arg) => typeof arg === "boolean",
is.undef = (arg) => typeof arg === "undefined",
is.def = (arg) => typeof arg === "defined",
is.arr = (arg) => Array.isArray(arg),
is.obj = (arg) => !Array.isArray(arg) && typeof arg === "object",
is.fun = (arg) => typeof arg === "function",
is.truthy = (arg) => Boolean(arg),
is.falsy = (arg) => !Boolean(arg)